- name: Configure Docker on Target Machine
  hosts: all
  become: yes

  tasks:
    ## The tasks are responsible to configure docker
    - name: Update apt-get repo
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install the latest version of Docker CE
      apt:
        pkg: docker-ce
        state: present
        update_cache: yes


### The tasks are responsible to configure Apache server 

    - name: Install pip package
      apt: 
          name: python3-pip
          state: present
          update_cache: yes

    - name: Install Docker SDK for Python
      pip:
          name: docker

    - name: Create Docker network for Apache server
      docker_network:
        name: apache_network
        driver_options: 
          com.docker.network.bridge.name: 'priv-apache-br1'
        ipam_config:
          - subnet: 172.168.10.0/30

    - name: Copying Default landing page
      copy:
          src: index.html
          dest: /usr/local/apache2/htdocs/
      register: copy_result
      notify: 
      - RestartApache

    - name: Start Apache Docker container
      docker_container:
          name: apache
          image: httpd:latest
          state: started
          restart_policy: always
          networks: 
          - name: apache_network
          ports:
          - "8080:80"
          volumes: 
          - /usr/local/apache2/htdocs/index.html:/usr/local/apache2/htdocs/index.html